import turtle
turtle.speed(100)

def drawsquare ():
    #line 1
    turtle.forward(180)

    #line 2
    turtle.right(90)
    turtle.forward(180)

    #line 3
    turtle.right(90)
    turtle.forward(180)

    #line 4
    turtle.right(90)
    turtle.forward(173)
    turtle.right(90)

def drawrectangle(numsquares):
    for i in range(numsquares):
        drawsquare()


drawrectangle(20)

turtle.up()
#move turtle 
turtle.forward(180)
turtle.left(90)
turtle.forward(140)
turtle.right(90)
turtle.down()
drawrectangle(20)
turtle.up()
#move turtle
turtle.left(90)
turtle.forward(140)
turtle.left(90)
turtle.down()
drawrectangle(20)
turtle.up()
#move turtle
turtle.left(90)
turtle.down()
drawrectangle(20)
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# turtle.forward(180)
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
# drawsquare()
turtle.exitonclick()